-include redis.dep
redis.lo: /Users/david/projects/whynottest/car-api/redis-6.2.0/redis.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/david/projects/whynottest/car-api/redis-6.2.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/david/projects/whynottest/car-api/redis-6.2.0/redis.c -o redis.lo  -MMD -MF redis.dep -MT redis.lo
-include redis_commands.dep
redis_commands.lo: /Users/david/projects/whynottest/car-api/redis-6.2.0/redis_commands.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/david/projects/whynottest/car-api/redis-6.2.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/david/projects/whynottest/car-api/redis-6.2.0/redis_commands.c -o redis_commands.lo  -MMD -MF redis_commands.dep -MT redis_commands.lo
-include library.dep
library.lo: /Users/david/projects/whynottest/car-api/redis-6.2.0/library.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/david/projects/whynottest/car-api/redis-6.2.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/david/projects/whynottest/car-api/redis-6.2.0/library.c -o library.lo  -MMD -MF library.dep -MT library.lo
-include redis_session.dep
redis_session.lo: /Users/david/projects/whynottest/car-api/redis-6.2.0/redis_session.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/david/projects/whynottest/car-api/redis-6.2.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/david/projects/whynottest/car-api/redis-6.2.0/redis_session.c -o redis_session.lo  -MMD -MF redis_session.dep -MT redis_session.lo
-include redis_array.dep
redis_array.lo: /Users/david/projects/whynottest/car-api/redis-6.2.0/redis_array.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/david/projects/whynottest/car-api/redis-6.2.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/david/projects/whynottest/car-api/redis-6.2.0/redis_array.c -o redis_array.lo  -MMD -MF redis_array.dep -MT redis_array.lo
-include redis_array_impl.dep
redis_array_impl.lo: /Users/david/projects/whynottest/car-api/redis-6.2.0/redis_array_impl.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/david/projects/whynottest/car-api/redis-6.2.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/david/projects/whynottest/car-api/redis-6.2.0/redis_array_impl.c -o redis_array_impl.lo  -MMD -MF redis_array_impl.dep -MT redis_array_impl.lo
-include redis_cluster.dep
redis_cluster.lo: /Users/david/projects/whynottest/car-api/redis-6.2.0/redis_cluster.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/david/projects/whynottest/car-api/redis-6.2.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/david/projects/whynottest/car-api/redis-6.2.0/redis_cluster.c -o redis_cluster.lo  -MMD -MF redis_cluster.dep -MT redis_cluster.lo
-include cluster_library.dep
cluster_library.lo: /Users/david/projects/whynottest/car-api/redis-6.2.0/cluster_library.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/david/projects/whynottest/car-api/redis-6.2.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/david/projects/whynottest/car-api/redis-6.2.0/cluster_library.c -o cluster_library.lo  -MMD -MF cluster_library.dep -MT cluster_library.lo
-include redis_sentinel.dep
redis_sentinel.lo: /Users/david/projects/whynottest/car-api/redis-6.2.0/redis_sentinel.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/david/projects/whynottest/car-api/redis-6.2.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/david/projects/whynottest/car-api/redis-6.2.0/redis_sentinel.c -o redis_sentinel.lo  -MMD -MF redis_sentinel.dep -MT redis_sentinel.lo
-include sentinel_library.dep
sentinel_library.lo: /Users/david/projects/whynottest/car-api/redis-6.2.0/sentinel_library.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/david/projects/whynottest/car-api/redis-6.2.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/david/projects/whynottest/car-api/redis-6.2.0/sentinel_library.c -o sentinel_library.lo  -MMD -MF sentinel_library.dep -MT sentinel_library.lo
-include backoff.dep
backoff.lo: /Users/david/projects/whynottest/car-api/redis-6.2.0/backoff.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/david/projects/whynottest/car-api/redis-6.2.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/david/projects/whynottest/car-api/redis-6.2.0/backoff.c -o backoff.lo  -MMD -MF backoff.dep -MT backoff.lo
$(phplibdir)/redis.la: ./redis.la
	$(LIBTOOL) --tag=CC --mode=install cp ./redis.la $(phplibdir)

./redis.la: $(shared_objects_redis) $(REDIS_SHARED_DEPENDENCIES)
	$(LIBTOOL) --tag=CC --mode=link $(CC) -shared $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_redis) $(REDIS_SHARED_LIBADD)

